# Application Name
spring.application.name=expense-tracker

# Server Port
server.port=${PORT:8080}

# MongoDB Configuration
spring.data.mongodb.uri=${MONGODB_URI}

# Format JSON outputs in response bodies cleanly
spring.jackson.serialization.indent_output=true