spring.application.name=expense-tracker
server.port=${PORT:8080}
spring.profiles.active=local
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/ExpenseTrackerDB}
spring.jackson.serialization.indent_output=true
