# Application Name
spring.application.name=expense-tracker

# Server Port
server.port=8080

# MongoDB Configuration
spring.mongodb.uri=mongodb://localhost:27017/ExpenseTrackerDB
spring.mongodb.database=ExpenseTrackerDB

# Format JSON outputs in response bodies cleanly
spring.jackson.serialization.indent_output=true

